export type AssetCategory = "gas" | "stablecoin" | "defi" | "ecosystem";
export type TokenType = "native" | "erc20" | "spl" | "btc";

export interface AssetDefinition {
  assetId: string;
  symbol: string;
  displayName: string;
  networkId: string;
  tokenType: TokenType;
  address: string;
  decimals: number;
  coingeckoId: string;
  category: AssetCategory;
  isStablecoin: boolean;
  isPaymentAsset: boolean;
  isDefaultVisible: boolean;
  sortPriority: number;
  swapSupported: boolean;
  bridgeSupported: boolean;
}

export const assetRegistry: AssetDefinition[] = [
  // ── Arbitrum ──
  {
    assetId: "arbitrum:ETH",
    symbol: "ETH",
    displayName: "Ether",
    networkId: "arbitrum",
    tokenType: "native",
    address: "",
    decimals: 18,
    coingeckoId: "ethereum",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "arbitrum:ARB",
    symbol: "ARB",
    displayName: "Arbitrum",
    networkId: "arbitrum",
    tokenType: "erc20",
    address: "0x912CE59144191C1204E64559FE8253a0e49E6548",
    decimals: 18,
    coingeckoId: "arbitrum",
    category: "ecosystem",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 10,
    swapSupported: true,
    bridgeSupported: false,
  },
  {
    assetId: "arbitrum:USDT",
    symbol: "USDT",
    displayName: "Tether USD",
    networkId: "arbitrum",
    tokenType: "erc20",
    address: "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9",
    decimals: 6,
    coingeckoId: "tether",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 1,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "arbitrum:USDC",
    symbol: "USDC",
    displayName: "USD Coin",
    networkId: "arbitrum",
    tokenType: "erc20",
    address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
    decimals: 6,
    coingeckoId: "usd-coin",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 2,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "arbitrum:GMX",
    symbol: "GMX",
    displayName: "GMX",
    networkId: "arbitrum",
    tokenType: "erc20",
    address: "0xfc5A1A6EB076a2C7aD06eD22C90d7E710E35ad0a",
    decimals: 18,
    coingeckoId: "gmx",
    category: "defi",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 20,
    swapSupported: true,
    bridgeSupported: false,
  },

  // ── Ethereum ──
  {
    assetId: "ethereum:ETH",
    symbol: "ETH",
    displayName: "Ether",
    networkId: "ethereum",
    tokenType: "native",
    address: "",
    decimals: 18,
    coingeckoId: "ethereum",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "ethereum:USDT",
    symbol: "USDT",
    displayName: "Tether USD",
    networkId: "ethereum",
    tokenType: "erc20",
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    decimals: 6,
    coingeckoId: "tether",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 1,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "ethereum:USDC",
    symbol: "USDC",
    displayName: "USD Coin",
    networkId: "ethereum",
    tokenType: "erc20",
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    decimals: 6,
    coingeckoId: "usd-coin",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 2,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "ethereum:LINK",
    symbol: "LINK",
    displayName: "Chainlink",
    networkId: "ethereum",
    tokenType: "erc20",
    address: "0x514910771AF9Ca656af840dff83E8264EcF986CA",
    decimals: 18,
    coingeckoId: "chainlink",
    category: "ecosystem",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 20,
    swapSupported: true,
    bridgeSupported: false,
  },
  {
    assetId: "ethereum:UNI",
    symbol: "UNI",
    displayName: "Uniswap",
    networkId: "ethereum",
    tokenType: "erc20",
    address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
    decimals: 18,
    coingeckoId: "uniswap",
    category: "ecosystem",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 21,
    swapSupported: true,
    bridgeSupported: false,
  },

  // ── BNB Chain ──
  {
    assetId: "bnb:BNB",
    symbol: "BNB",
    displayName: "BNB",
    networkId: "bnb",
    tokenType: "native",
    address: "",
    decimals: 18,
    coingeckoId: "binancecoin",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "bnb:USDT",
    symbol: "USDT",
    displayName: "Tether USD",
    networkId: "bnb",
    tokenType: "erc20",
    address: "0x55d398326f99059fF775485246999027B3197955",
    decimals: 18,
    coingeckoId: "tether",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 1,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "bnb:USDC",
    symbol: "USDC",
    displayName: "USD Coin",
    networkId: "bnb",
    tokenType: "erc20",
    address: "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
    decimals: 18,
    coingeckoId: "usd-coin",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 2,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "bnb:CAKE",
    symbol: "CAKE",
    displayName: "PancakeSwap",
    networkId: "bnb",
    tokenType: "erc20",
    address: "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82",
    decimals: 18,
    coingeckoId: "pancakeswap-token",
    category: "defi",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 20,
    swapSupported: true,
    bridgeSupported: false,
  },
  {
    assetId: "bnb:FDUSD",
    symbol: "FDUSD",
    displayName: "First Digital USD",
    networkId: "bnb",
    tokenType: "erc20",
    address: "0xc5f0f7b66764F6ec8C8Dff7BA683102295E16409",
    decimals: 18,
    coingeckoId: "first-digital-usd",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 15,
    swapSupported: true,
    bridgeSupported: false,
  },

  // ── Avalanche ──
  {
    assetId: "avalanche:AVAX",
    symbol: "AVAX",
    displayName: "Avalanche",
    networkId: "avalanche",
    tokenType: "native",
    address: "",
    decimals: 18,
    coingeckoId: "avalanche-2",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "avalanche:USDT",
    symbol: "USDT",
    displayName: "Tether USD",
    networkId: "avalanche",
    tokenType: "erc20",
    address: "0x9702230A8Ea53601f5cD2dc00fDBc13d4dF4A8c7",
    decimals: 6,
    coingeckoId: "tether",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 1,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "avalanche:USDC",
    symbol: "USDC",
    displayName: "USD Coin",
    networkId: "avalanche",
    tokenType: "erc20",
    address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
    decimals: 6,
    coingeckoId: "usd-coin",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 2,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "avalanche:JOE",
    symbol: "JOE",
    displayName: "Trader Joe",
    networkId: "avalanche",
    tokenType: "erc20",
    address: "0x6e84a6216eA6dACC71eE8E6b0a5B7322EEbC0fDd",
    decimals: 18,
    coingeckoId: "joe",
    category: "defi",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 20,
    swapSupported: true,
    bridgeSupported: false,
  },
  {
    assetId: "avalanche:QI",
    symbol: "QI",
    displayName: "BENQI",
    networkId: "avalanche",
    tokenType: "erc20",
    address: "0x8729438EB15e2C8B576fCc6AeCdA6A148776C0F5",
    decimals: 18,
    coingeckoId: "benqi",
    category: "defi",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 21,
    swapSupported: true,
    bridgeSupported: false,
  },

  // ── Solana ──
  {
    assetId: "solana:SOL",
    symbol: "SOL",
    displayName: "Solana",
    networkId: "solana",
    tokenType: "native",
    address: "",
    decimals: 9,
    coingeckoId: "solana",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "solana:USDT",
    symbol: "USDT",
    displayName: "Tether USD",
    networkId: "solana",
    tokenType: "spl",
    address: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
    decimals: 6,
    coingeckoId: "tether",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 1,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "solana:USDC",
    symbol: "USDC",
    displayName: "USD Coin",
    networkId: "solana",
    tokenType: "spl",
    address: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    decimals: 6,
    coingeckoId: "usd-coin",
    category: "stablecoin",
    isStablecoin: true,
    isPaymentAsset: true,
    isDefaultVisible: true,
    sortPriority: 2,
    swapSupported: true,
    bridgeSupported: true,
  },
  {
    assetId: "solana:JUP",
    symbol: "JUP",
    displayName: "Jupiter",
    networkId: "solana",
    tokenType: "spl",
    address: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    decimals: 6,
    coingeckoId: "jupiter-exchange-solana",
    category: "defi",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 20,
    swapSupported: true,
    bridgeSupported: false,
  },
  {
    assetId: "solana:PYTH",
    symbol: "PYTH",
    displayName: "Pyth Network",
    networkId: "solana",
    tokenType: "spl",
    address: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    decimals: 6,
    coingeckoId: "pyth-network",
    category: "ecosystem",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: false,
    sortPriority: 21,
    swapSupported: true,
    bridgeSupported: false,
  },

  // ── Bitcoin ──
  {
    assetId: "bitcoin:BTC",
    symbol: "BTC",
    displayName: "Bitcoin",
    networkId: "bitcoin",
    tokenType: "btc",
    address: "",
    decimals: 8,
    coingeckoId: "bitcoin",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: false,
    bridgeSupported: false,
  },

  // ── Dogecoin ──
  {
    assetId: "dogecoin:DOGE",
    symbol: "DOGE",
    displayName: "Dogecoin",
    networkId: "dogecoin",
    tokenType: "btc",
    address: "",
    decimals: 8,
    coingeckoId: "dogecoin",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: false,
    bridgeSupported: false,
  },

  // ── Zcash ──
  {
    assetId: "zcash:ZEC",
    symbol: "ZEC",
    displayName: "Zcash",
    networkId: "zcash",
    tokenType: "btc",
    address: "",
    decimals: 8,
    coingeckoId: "zcash",
    category: "gas",
    isStablecoin: false,
    isPaymentAsset: false,
    isDefaultVisible: true,
    sortPriority: 0,
    swapSupported: false,
    bridgeSupported: false,
  },
];

export function getAssetsForNetwork(networkId: string): AssetDefinition[] {
  return assetRegistry
    .filter((a) => a.networkId === networkId)
    .sort((a, b) => a.sortPriority - b.sortPriority);
}

export function getAsset(assetId: string): AssetDefinition | undefined {
  return assetRegistry.find((a) => a.assetId === assetId);
}

export function getPaymentAssets(): AssetDefinition[] {
  return assetRegistry.filter((a) => a.isPaymentAsset);
}

export function getStablecoins(): AssetDefinition[] {
  return assetRegistry.filter((a) => a.isStablecoin);
}
